[package]
name = "kerything-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "kerythingd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
kerything-core = { path = "../kerything-core" }
serde.workspace = true
serde_json.workspace = true
xdg.workspace = true
