[package]
name = "oxidex"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
crossbeam-channel.workspace = true
eframe.workspace = true
egui_extras.workspace = true
oxidex-client = { path = "../oxidex-client" }
oxidex-core = { path = "../oxidex-core" }
open.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
